### ISSUE TITLE
Request: can you add properties to customise the Stop button layout?

### ISSUE THREAD

**Issue by funnel20** [tularovbeslan/InStatDownloadButton#1]
This is an awesome lib, thank you very much.
We have one request, to change the appearance of the Stop button.
I see it's created by code.
Is it possible to have 2 new properties, so we can style it exactly as in the Apple Music app?

1. Corner radius
2. Relative size with respect to the circle

**Comment by mpkupriyanov** [comment]
Hi!
Can you attach a screenshot how it looks like?

**Comment by funnel20** [comment]
That's awesome, thank you very much.
When do you think it will be released?

**Comment by tularovbeslan** [comment]
Released in 1.2.2. You can use it now, also use stopRelativeSize to set the relative size as a percentage.

**Comment by funnel20** [comment]
Thanks for the quick release.
May I ask why the release is called "1.2.2" and not "1.2.0"?
